/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.nfactory.crudmysql.gui;

/**
 *
 * @author Antoine
 */
public class Front extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Front() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        clientsButton = new javax.swing.JButton();
        offresButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        rightLayout = new javax.swing.JPanel();
        rightContainer = new javax.swing.JPanel();
        loginContainer = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        clientListContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        offresContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        offers = new javax.swing.JPanel();
        offer = new javax.swing.JPanel();
        offerTitle = new javax.swing.JLabel();
        offerConditionTitle = new javax.swing.JLabel();
        offerConditionVariable = new javax.swing.JLabel();
        offerPlafondVariable = new javax.swing.JLabel();
        offerPlafondTitle = new javax.swing.JLabel();
        offerTauxVariable = new javax.swing.JLabel();
        offerTauxTitle = new javax.swing.JLabel();
        offerDescriptionVariable = new javax.swing.JLabel();
        offerModifier = new javax.swing.JButton();
        statsContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clientContainer = new javax.swing.JPanel();
        clientName = new javax.swing.JLabel();
        clientInfoContainer = new javax.swing.JPanel();
        offerTitle1 = new javax.swing.JLabel();
        clientSurnameTitle = new javax.swing.JLabel();
        ClientSurnameVariable = new javax.swing.JLabel();
        clientNameVariable = new javax.swing.JLabel();
        clientNameTitle = new javax.swing.JLabel();
        clientAgeVariable = new javax.swing.JLabel();
        clientAgeTitle = new javax.swing.JLabel();
        clientBirthdateTitle = new javax.swing.JLabel();
        clientBirthdateVariable = new javax.swing.JLabel();
        clientFamilleVariable = new javax.swing.JLabel();
        clientFamilleTitle = new javax.swing.JLabel();
        clientMailVariable = new javax.swing.JLabel();
        clientMailTitle = new javax.swing.JLabel();
        clientTelVariable = new javax.swing.JLabel();
        clientTelTitle = new javax.swing.JLabel();
        clientEnfantVariable = new javax.swing.JLabel();
        clientEnfantTitle = new javax.swing.JLabel();
        clientProVariable = new javax.swing.JLabel();
        clientProTitle = new javax.swing.JLabel();
        clientModifier = new javax.swing.JButton();
        clientInfoContainer1 = new javax.swing.JPanel();
        offerTitle2 = new javax.swing.JLabel();
        clientInfoContainer2 = new javax.swing.JPanel();
        offerTitle3 = new javax.swing.JLabel();
        clientInfoContainer3 = new javax.swing.JPanel();
        offerTitle4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(60, 60, 60, 60));
        setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(204, 51, 0));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(24, 171, 232));
        jPanel2.setPreferredSize(new java.awt.Dimension(139, 720));

        jPanel1.setBackground(new java.awt.Color(24, 171, 232));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(24, 171, 232));
        jPanel4.setLayout(new java.awt.GridLayout(3, 1, 0, 20));

        clientsButton.setBackground(new java.awt.Color(255, 255, 255));
        clientsButton.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        clientsButton.setText("Clients");
        clientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsButtonActionPerformed(evt);
            }
        });
        jPanel4.add(clientsButton);

        offresButton.setBackground(new java.awt.Color(255, 255, 255));
        offresButton.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        offresButton.setText("Offres");
        offresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offresButtonActionPerformed(evt);
            }
        });
        jPanel4.add(offresButton);

        statsButton.setBackground(new java.awt.Color(255, 255, 255));
        statsButton.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        statsButton.setText("Statistiques");
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        jPanel4.add(statsButton);

        jPanel1.add(jPanel4, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1074, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, java.awt.BorderLayout.LINE_START);

        rightLayout.setBackground(new java.awt.Color(255, 255, 255));
        rightLayout.setLayout(new java.awt.CardLayout());

        rightContainer.setBackground(new java.awt.Color(255, 255, 255));

        loginContainer.setBackground(new java.awt.Color(255, 255, 255));
        loginContainer.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        loginContainer.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        loginLabel.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(24, 171, 232));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Connexion");
        loginContainer.add(loginLabel);

        idField.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        idField.setForeground(new java.awt.Color(112, 112, 112));
        idField.setText("Identifiant");
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        loginContainer.add(idField);

        PasswordField.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(112, 112, 112));
        PasswordField.setText("Mot de passe");
        PasswordField.setPreferredSize(new java.awt.Dimension(86, 22));
        loginContainer.add(PasswordField);

        loginButton.setBackground(new java.awt.Color(24, 171, 232));
        loginButton.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Se connecter");
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginContainer.add(loginButton);

        clientListContainer.setBackground(new java.awt.Color(255, 255, 255));
        clientListContainer.setVisible(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 171, 232));
        jLabel1.setText("Liste des prospects");

        jTable1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Age", "Date d'adhésion", "Code postal", "Ville"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout clientListContainerLayout = new javax.swing.GroupLayout(clientListContainer);
        clientListContainer.setLayout(clientListContainerLayout);
        clientListContainerLayout.setHorizontalGroup(
            clientListContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientListContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(clientListContainerLayout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel1)
                .addGap(387, 387, 387))
        );
        clientListContainerLayout.setVerticalGroup(
            clientListContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientListContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(888, Short.MAX_VALUE))
        );

        offresContainer.setBackground(new java.awt.Color(255, 255, 255));
        offresContainer.setVisible(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(24, 171, 232));
        jLabel2.setText("Liste des offres");

        offers.setBackground(new java.awt.Color(255, 255, 255));
        offers.setLayout(new java.awt.GridLayout(2, 3, 30, 30));

        offer.setBackground(new java.awt.Color(24, 171, 232));
        offer.setForeground(new java.awt.Color(255, 255, 255));
        offer.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offer.setMinimumSize(new java.awt.Dimension(336, 271));
        offer.setPreferredSize(new java.awt.Dimension(336, 271));

        offerTitle.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        offerTitle.setForeground(new java.awt.Color(255, 255, 255));
        offerTitle.setText("Titre");

        offerConditionTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerConditionTitle.setForeground(new java.awt.Color(255, 255, 255));
        offerConditionTitle.setText("Conditions :");

        offerConditionVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerConditionVariable.setForeground(new java.awt.Color(255, 255, 255));
        offerConditionVariable.setText("$condition");

        offerPlafondVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerPlafondVariable.setForeground(new java.awt.Color(255, 255, 255));
        offerPlafondVariable.setText("$plafond");

        offerPlafondTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerPlafondTitle.setForeground(new java.awt.Color(255, 255, 255));
        offerPlafondTitle.setText("Plafond :");

        offerTauxVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerTauxVariable.setForeground(new java.awt.Color(255, 255, 255));
        offerTauxVariable.setText("$taux");

        offerTauxTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerTauxTitle.setForeground(new java.awt.Color(255, 255, 255));
        offerTauxTitle.setText("Taux :");

        offerDescriptionVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerDescriptionVariable.setForeground(new java.awt.Color(255, 255, 255));
        offerDescriptionVariable.setText("$description");

        offerModifier.setBackground(new java.awt.Color(255, 255, 255));
        offerModifier.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        offerModifier.setForeground(new java.awt.Color(24, 171, 232));
        offerModifier.setText("Modifier");
        offerModifier.setMaximumSize(new java.awt.Dimension(147, 47));
        offerModifier.setMinimumSize(new java.awt.Dimension(147, 47));

        javax.swing.GroupLayout offerLayout = new javax.swing.GroupLayout(offer);
        offer.setLayout(offerLayout);
        offerLayout.setHorizontalGroup(
            offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offerLayout.createSequentialGroup()
                .addGroup(offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(offerLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(offerTitle))
                    .addGroup(offerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(offerLayout.createSequentialGroup()
                                .addComponent(offerConditionTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(offerConditionVariable))
                            .addGroup(offerLayout.createSequentialGroup()
                                .addComponent(offerPlafondTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(offerPlafondVariable))
                            .addGroup(offerLayout.createSequentialGroup()
                                .addComponent(offerTauxTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(offerTauxVariable))
                            .addComponent(offerDescriptionVariable))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, offerLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(offerModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        offerLayout.setVerticalGroup(
            offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(offerTitle)
                .addGap(18, 18, 18)
                .addGroup(offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offerConditionTitle)
                    .addComponent(offerConditionVariable))
                .addGap(18, 18, 18)
                .addGroup(offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offerPlafondTitle)
                    .addComponent(offerPlafondVariable))
                .addGap(18, 18, 18)
                .addGroup(offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offerTauxTitle)
                    .addComponent(offerTauxVariable))
                .addGap(18, 18, 18)
                .addComponent(offerDescriptionVariable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(offerModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        offers.add(offer);

        javax.swing.GroupLayout offresContainerLayout = new javax.swing.GroupLayout(offresContainer);
        offresContainer.setLayout(offresContainerLayout);
        offresContainerLayout.setHorizontalGroup(
            offresContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offresContainerLayout.createSequentialGroup()
                .addGroup(offresContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(offresContainerLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jLabel2))
                    .addGroup(offresContainerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(offers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(456, 456, 456))
        );
        offresContainerLayout.setVerticalGroup(
            offresContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offresContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(offers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statsContainer.setBackground(new java.awt.Color(255, 255, 255));
        statsContainer.setVisible(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 171, 232));
        jLabel3.setText("Statistiques");

        javax.swing.GroupLayout statsContainerLayout = new javax.swing.GroupLayout(statsContainer);
        statsContainer.setLayout(statsContainerLayout);
        statsContainerLayout.setHorizontalGroup(
            statsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsContainerLayout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel3)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        statsContainerLayout.setVerticalGroup(
            statsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(1369, Short.MAX_VALUE))
        );

        clientContainer.setBackground(new java.awt.Color(255, 255, 255));
        clientContainer.setPreferredSize(new java.awt.Dimension(1141, 720));
        offresContainer.setVisible(false);

        clientName.setBackground(new java.awt.Color(255, 255, 255));
        clientName.setFont(new java.awt.Font("Montserrat", 1, 30)); // NOI18N
        clientName.setForeground(new java.awt.Color(24, 171, 232));
        clientName.setText("$nom");

        clientInfoContainer.setBackground(new java.awt.Color(24, 171, 232));
        clientInfoContainer.setForeground(new java.awt.Color(255, 255, 255));
        clientInfoContainer.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientInfoContainer.setMinimumSize(new java.awt.Dimension(344, 569));
        clientInfoContainer.setPreferredSize(new java.awt.Dimension(344, 569));

        offerTitle1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        offerTitle1.setForeground(new java.awt.Color(255, 255, 255));
        offerTitle1.setText("Informations");

        clientSurnameTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientSurnameTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientSurnameTitle.setText("Nom :");

        ClientSurnameVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        ClientSurnameVariable.setForeground(new java.awt.Color(255, 255, 255));
        ClientSurnameVariable.setText("$nom");

        clientNameVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientNameVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientNameVariable.setText("$prenom");

        clientNameTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientNameTitle.setText("Prénom :");

        clientAgeVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientAgeVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientAgeVariable.setText("$age");

        clientAgeTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientAgeTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientAgeTitle.setText("Age :");

        clientBirthdateTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientBirthdateTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientBirthdateTitle.setText("Date de naissance :");

        clientBirthdateVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientBirthdateVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientBirthdateVariable.setText("$birthdate");

        clientFamilleVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientFamilleVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientFamilleVariable.setText("$famille");

        clientFamilleTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientFamilleTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientFamilleTitle.setText("Situation familiale");

        clientMailVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientMailVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientMailVariable.setText("$mail");

        clientMailTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientMailTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientMailTitle.setText("E-mail :");

        clientTelVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientTelVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientTelVariable.setText("$tel");

        clientTelTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientTelTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientTelTitle.setText("Numéro de téléphone :");

        clientEnfantVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientEnfantVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientEnfantVariable.setText("$enfants");

        clientEnfantTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientEnfantTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientEnfantTitle.setText("Nombre d'enfants :");

        clientProVariable.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientProVariable.setForeground(new java.awt.Color(255, 255, 255));
        clientProVariable.setText("$pro");

        clientProTitle.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientProTitle.setForeground(new java.awt.Color(255, 255, 255));
        clientProTitle.setText("Situation professionnelle :");

        clientModifier.setBackground(new java.awt.Color(255, 255, 255));
        clientModifier.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientModifier.setForeground(new java.awt.Color(24, 171, 232));
        clientModifier.setText("Modifier");
        clientModifier.setMaximumSize(new java.awt.Dimension(147, 47));
        clientModifier.setMinimumSize(new java.awt.Dimension(147, 47));

        javax.swing.GroupLayout clientInfoContainerLayout = new javax.swing.GroupLayout(clientInfoContainer);
        clientInfoContainer.setLayout(clientInfoContainerLayout);
        clientInfoContainerLayout.setHorizontalGroup(
            clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientNameTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientNameVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientAgeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientAgeVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientSurnameTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClientSurnameVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientBirthdateTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientBirthdateVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientFamilleTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientFamilleVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientMailTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientMailVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientTelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientTelVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientEnfantTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientEnfantVariable))
                    .addGroup(clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientProTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientProVariable)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientInfoContainerLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(clientModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientInfoContainerLayout.createSequentialGroup()
                        .addComponent(offerTitle1)
                        .addGap(112, 112, 112))))
        );
        clientInfoContainerLayout.setVerticalGroup(
            clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(offerTitle1)
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientSurnameTitle)
                    .addComponent(ClientSurnameVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTitle)
                    .addComponent(clientNameVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientAgeTitle)
                    .addComponent(clientAgeVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientBirthdateTitle)
                    .addComponent(clientBirthdateVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFamilleTitle)
                    .addComponent(clientFamilleVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientMailTitle)
                    .addComponent(clientMailVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTelTitle)
                    .addComponent(clientTelVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientEnfantTitle)
                    .addComponent(clientEnfantVariable))
                .addGap(18, 18, 18)
                .addGroup(clientInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientProTitle)
                    .addComponent(clientProVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(clientModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        clientInfoContainer1.setBackground(new java.awt.Color(24, 171, 232));
        clientInfoContainer1.setForeground(new java.awt.Color(255, 255, 255));
        clientInfoContainer1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientInfoContainer1.setMinimumSize(new java.awt.Dimension(344, 271));
        clientInfoContainer1.setPreferredSize(new java.awt.Dimension(344, 271));

        offerTitle2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        offerTitle2.setForeground(new java.awt.Color(255, 255, 255));
        offerTitle2.setText("Offres disponibles");

        javax.swing.GroupLayout clientInfoContainer1Layout = new javax.swing.GroupLayout(clientInfoContainer1);
        clientInfoContainer1.setLayout(clientInfoContainer1Layout);
        clientInfoContainer1Layout.setHorizontalGroup(
            clientInfoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainer1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(offerTitle2)
                .addGap(89, 89, 89))
        );
        clientInfoContainer1Layout.setVerticalGroup(
            clientInfoContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainer1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(offerTitle2)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        clientInfoContainer2.setBackground(new java.awt.Color(24, 171, 232));
        clientInfoContainer2.setForeground(new java.awt.Color(255, 255, 255));
        clientInfoContainer2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientInfoContainer2.setMinimumSize(new java.awt.Dimension(344, 569));
        clientInfoContainer2.setPreferredSize(new java.awt.Dimension(344, 569));

        offerTitle3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        offerTitle3.setForeground(new java.awt.Color(255, 255, 255));
        offerTitle3.setText("Comptes");

        javax.swing.GroupLayout clientInfoContainer2Layout = new javax.swing.GroupLayout(clientInfoContainer2);
        clientInfoContainer2.setLayout(clientInfoContainer2Layout);
        clientInfoContainer2Layout.setHorizontalGroup(
            clientInfoContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientInfoContainer2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(offerTitle3)
                .addGap(131, 131, 131))
        );
        clientInfoContainer2Layout.setVerticalGroup(
            clientInfoContainer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainer2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(offerTitle3)
                .addContainerGap(525, Short.MAX_VALUE))
        );

        clientInfoContainer3.setBackground(new java.awt.Color(24, 171, 232));
        clientInfoContainer3.setForeground(new java.awt.Color(255, 255, 255));
        clientInfoContainer3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        clientInfoContainer3.setMinimumSize(new java.awt.Dimension(344, 271));

        offerTitle4.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        offerTitle4.setForeground(new java.awt.Color(255, 255, 255));
        offerTitle4.setText("Offres proposées");

        javax.swing.GroupLayout clientInfoContainer3Layout = new javax.swing.GroupLayout(clientInfoContainer3);
        clientInfoContainer3.setLayout(clientInfoContainer3Layout);
        clientInfoContainer3Layout.setHorizontalGroup(
            clientInfoContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainer3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(offerTitle4)
                .addGap(95, 95, 95))
        );
        clientInfoContainer3Layout.setVerticalGroup(
            clientInfoContainer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientInfoContainer3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(offerTitle4)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout clientContainerLayout = new javax.swing.GroupLayout(clientContainer);
        clientContainer.setLayout(clientContainerLayout);
        clientContainerLayout.setHorizontalGroup(
            clientContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(clientContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientContainerLayout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(clientName))
                    .addGroup(clientContainerLayout.createSequentialGroup()
                        .addComponent(clientInfoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(clientContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientInfoContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientInfoContainer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(clientInfoContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        clientContainerLayout.setVerticalGroup(
            clientContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(clientName)
                .addGap(18, 18, 18)
                .addGroup(clientContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clientInfoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(clientContainerLayout.createSequentialGroup()
                        .addComponent(clientInfoContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clientInfoContainer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clientInfoContainer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightContainerLayout = new javax.swing.GroupLayout(rightContainer);
        rightContainer.setLayout(rightContainerLayout);
        rightContainerLayout.setHorizontalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clientListContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(offresContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clientContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(statsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightContainerLayout.setVerticalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightContainerLayout.createSequentialGroup()
                .addContainerGap(979, Short.MAX_VALUE)
                .addComponent(loginContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clientListContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightContainerLayout.createSequentialGroup()
                    .addComponent(offresContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(clientContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(statsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightLayout.add(rightContainer, "card2");

        jPanel3.add(rightLayout, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void offresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offresButtonActionPerformed
        loginContainer.setVisible(false);
        offresContainer.setVisible(true);
        statsContainer.setVisible(false);
        clientListContainer.setVisible(false);
        clientContainer.setVisible(false);

    }//GEN-LAST:event_offresButtonActionPerformed

    private void clientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsButtonActionPerformed

        loginContainer.setVisible(false);
        offresContainer.setVisible(false);
        statsContainer.setVisible(false);
        clientListContainer.setVisible(true);
        clientContainer.setVisible(false);
        
    }//GEN-LAST:event_clientsButtonActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        loginContainer.setVisible(false);
        offresContainer.setVisible(false);
        statsContainer.setVisible(true);
        clientListContainer.setVisible(false);
        clientContainer.setVisible(false);
    }//GEN-LAST:event_statsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientSurnameVariable;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel clientAgeTitle;
    private javax.swing.JLabel clientAgeVariable;
    private javax.swing.JLabel clientBirthdateTitle;
    private javax.swing.JLabel clientBirthdateVariable;
    private javax.swing.JPanel clientContainer;
    private javax.swing.JLabel clientEnfantTitle;
    private javax.swing.JLabel clientEnfantVariable;
    private javax.swing.JLabel clientFamilleTitle;
    private javax.swing.JLabel clientFamilleVariable;
    private javax.swing.JPanel clientInfoContainer;
    private javax.swing.JPanel clientInfoContainer1;
    private javax.swing.JPanel clientInfoContainer2;
    private javax.swing.JPanel clientInfoContainer3;
    private javax.swing.JPanel clientListContainer;
    private javax.swing.JLabel clientMailTitle;
    private javax.swing.JLabel clientMailVariable;
    private javax.swing.JButton clientModifier;
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel clientNameTitle;
    private javax.swing.JLabel clientNameVariable;
    private javax.swing.JLabel clientProTitle;
    private javax.swing.JLabel clientProVariable;
    private javax.swing.JLabel clientSurnameTitle;
    private javax.swing.JLabel clientTelTitle;
    private javax.swing.JLabel clientTelVariable;
    private javax.swing.JButton clientsButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel offer;
    private javax.swing.JLabel offerConditionTitle;
    private javax.swing.JLabel offerConditionVariable;
    private javax.swing.JLabel offerDescriptionVariable;
    private javax.swing.JButton offerModifier;
    private javax.swing.JLabel offerPlafondTitle;
    private javax.swing.JLabel offerPlafondVariable;
    private javax.swing.JLabel offerTauxTitle;
    private javax.swing.JLabel offerTauxVariable;
    private javax.swing.JLabel offerTitle;
    private javax.swing.JLabel offerTitle1;
    private javax.swing.JLabel offerTitle2;
    private javax.swing.JLabel offerTitle3;
    private javax.swing.JLabel offerTitle4;
    private javax.swing.JPanel offers;
    private javax.swing.JButton offresButton;
    private javax.swing.JPanel offresContainer;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel rightLayout;
    private javax.swing.JButton statsButton;
    private javax.swing.JPanel statsContainer;
    // End of variables declaration//GEN-END:variables
}
